[package]
name = "historian-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
thiserror.workspace = true
prost = "0.13"
tonic = "0.12"

[build-dependencies]
tonic-build = "0.12"
